
project_id = "wjebryxdefcgsxsqomac"

[functions.checkout-session]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.team-build-request]
verify_jwt = true

[functions.alerts-availability]
verify_jwt = true

[functions.log-security-event]
verify_jwt = false

[functions.generate-all-partner-logos]
verify_jwt = true

[functions.notify]
verify_jwt = false

[functions.run-matcher]
verify_jwt = false

[functions.discord-interactions]
verify_jwt = false

[functions.discord-link]
verify_jwt = false

[functions.discord-bot-sender]

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.sms-status]
verify_jwt = false

[functions.admin-actions]
verify_jwt = true

